parameters:

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    # Listeners
    App\EventListener\UserCreationListener:
        tags:
            - { name: doctrine.event_listener, event: prePersist, entity: App\Entity\User }

    App\EventListener\ArticleCreationListener:
        tags:
            - { name: doctrine.event_listener, event: prePersist, entity: App\Entity\Article }
